DATA SEGMENT
    X DW 1000H
DATA ENDS
ASSUME CS:CODE,DS:DATA
CODE SEGMENT
    START:
    MOV AX,DATA
    MOV DS,AX 
    MOV AX,X
    MOV SI, OFFSET X
    MOV BYTE PTR [SI],0002H
    MOV AX,X
CODE ENDS
END START
 